apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: 
   name: dev-role
   namespace: dev
rules:
 - apiGroups: [""]   # "" indicates the core Api Group
   resources: ["pods"]
   verbs: ["get", "create", "list", "delete"]