apiVersion: v1
kind: Service
metadata:
  name: utc-service                           
spec:
  type: NodePort
  selector:
    app: nginx
    env: dev
  ports:
  - name: utrains-service-port
    protocol: TCP
    port: 80
    targetPort: 8082
    nodePort: 30001 # Port between 30,000 - 32,767