apiVersion: v1
kind: Service
metadata:
  name: utc-service                           
spec:
  type: LoadBalancer
  selector:
    app: httpd
  ports:
  - name: httpd-service-port
    protocol: TCP
    port: 80
    targetPort: 80